## 1
name: Android Build
## Actions that will be executed when you push code currently none
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check Lint
        run: sudo ./gradlew lintDebug

      #      - name: Run tests
      #        run: sudo ./gradlew test

      - name: Build with Gradle
        run: sudo ./gradlew build

#on:
#  # Trigger the workflow on push or pull request,
#  # but only for the main branch
#  push:
#    branches:
#      - main
#  pull_request:
#    branches:
#      - main
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v1
#
#      - name: Set Up JDK
#        uses: actions/setup-java@v1
#        with:
#          java-version: 1.8
#
#        - name: Run Tests
#          run: ./gradlew test

#        -name: Build Project
#         run: ./gradlew assemble


